### ISSUE TITLE
Issue with ProTrac?

### ISSUE THREAD

**Issue by gp79** [pschreiner/piClusterBuster#1]
Hi!
I am trying to run piClusterBuster on some test fastq files but the script doesn't get past proTRAC...
This is the log file down here, any idea of what could be wrong?
Thank you in advance!

running
  '/usr/lib/R/bin/R --slave --no-restore --vanilla --file=./bin/piClusterBuster.R --args -fq /osc-fs_home/giovanni/IIT/DIV0-1.fastq -x /home/scratch/moirai/genome/mm10.fa -gndb /home/giovanni/Mus_musculus.GRCm38.cds.all.fa -tedb /home/giovanni/src/tebreak/lib/teref.mouse.fa -ncbidb NA -n 5 -p 8 --verbose -gid Mouse'

WARNING: unknown gui '/home/giovanni/Mus_musculus.GRCm38.cds.all.fa', using X11

> ags <- commandArgs(TRUE)
> args <- processArgs(ags)
> 
> wd<-paste(getwd(), "/", sep="")
> 
> ####################################
> ##     Step 0: User Arguments     ##
> ####################################
> ## Setting Argument Defaults
> if(is.null(args$x))	{ print_help(wd, "Reference genome was not indicated"); q(save="no") 
+ } else { ref_gen<-normalizePath(args$x) }
> 
> if(is.null(args$fa) && is.null(args$fq) && is.null(args$bed))	{ print_help(wd, "No FASTA, FASTQ, nor piRNA Cluster file was indicated"); q(save="no") }
> if(!is.null(args$fa)) {
+ 	fa <- normalizePath(args$fa);
+ 	fq <- FALSE;
+ 	bed <- FALSE;
+         picall <- FALSE;
+ }
> if(!is.null(args$fq)) {
+ 	fa <- FALSE;
+         fq <- normalizePath(args$fq);
+         bed <- FALSE;
+         picall <- TRUE;
+ }
> if(!is.null(args$bed)) { 
+ 	fa <- FALSE;
+ 	fq <- FALSE;
+ 	bed <- normalizePath(args$bed); 
+ 	picall <- FALSE;
+ 	pi_loci <- read.table(bed);
+ }
> 
> num_clusters <- 5 
> if(!is.null(args$n))	{ num_clusters <- args$n }
> 
> ncbi_nt <- "FALSE"
> if(!is.null(args$ncbidb)) { ncbi_nt <- normalizePath(args$ncbidb) }
Warning message:
In normalizePath(args$ncbidb) : path[1]="NA": No such file or directory
> 
> if(is.null(args$gndb)) { print_help(wd, "No Gene database was indicated."); q(save="no");
+ } else	{ gn_set<-normalizePath(args$gndb) }
> 
> if(is.null(args$tedb)) { print_help(wd, "No TE database was indicated.  You can choose to have piClusterBuster retrieve the database by using -tedb \"NA\""); q(save="no")
+ } else	{ te_set<-normalizePath(args$tedb) }
> 
> if(is.null(args$qsub)) { qsub<-FALSE
+ } else	{ qsub<-TRUE }
> 
> if(is.null(args$srun)) { srun<-FALSE
+ } else  { srun<-TRUE; qsub<-FALSE }
> 
> if(is.null(args$d)) { setwd(wd)
+ } else	{ setwd(args$d) }
> 
> if(is.null(args$gid)) { gid<-"genome"
+ } else	{ gid<-args$gid }
> 
> if(is.null(args$go)) { go<-FALSE
+ } else  { go<-TRUE }
> 
> if(is.null(args$allsrna)) { allsrna<-FALSE
+ } else	{ allsrna<-TRUE }
> 
> if(is.null(args$verbose)) { verbose<-FALSE
+ } else { verbose<-TRUE  }
> 
> ## Check for and Load Appropriate Libraries
> install_unloadedLibs(c("Biostrings", "systemPipeR", "plyr", "doMC", "R.utils", "qcc", "plyr", "gProfileR", "seqinr"))
Bioconductor version 3.4 (BiocInstaller 1.24.0), ?biocLite for help
A new version of Bioconductor is available after installing the most recent
  version of R; see http://bioconductor.org/install
[1] "Libraries Installed"
> suppressPackageStartupMessages(library(Biostrings)); suppressPackageStartupMessages(library(seqinr)); suppressPackageStartupMessages(library(systemPipeR)); suppressPackageStartupMessages(library(foreach)); suppressPackageStartupMessages(library(doMC)); suppressPackageStartupMessages(library(R.utils)); suppressPackageStartupMessages(library(qcc)); suppressPackageStartupMessages(library(plyr)); suppressPackageStartupMessages(library(gProfileR));
> source("./bin/piClusterBuster_source.R")
> 
> ## Option to run in parallel (and haven't specified number of cores)
> if(is.null(args$p)) { threads <- 1; registerDoMC(threads)
+ } else	{ threads<-args$p; registerDoMC(threads) }
> 
> ## Provide update 3
> cat(sprintf("\n", "R Libraries Loaded", "\n"))

> 
> ##########################################
> ##	Step 1: Filter piRNAs and	##
> ## 	map piRNAs to reference genome	##
> ## 	(if BAM file is not provided)	##
> ##########################################
> results_dir <- paste(wd, gid,"_results",sep=""); 
> if(file.exists(results_dir)) { system(paste("mv -f", results_dir, paste(results_dir, "-OLD", sep=""), sep=" ")); dir.create(paste(results_dir, sep="")); setwd(results_dir)
+ } else { dir.create(paste(results_dir, sep="")); setwd(results_dir) }  
> results_dir <- paste(results_dir,"/",sep="");
> 
> setwd(results_dir)
> 
> if(fq != "FALSE" && !isTRUE(allsrna)) { fq <- filterpiRNAs(fq, 24) } # Filter out non-piRNAs (by length)  FIXXXXXX: confirm this works?
> 
> ##########################################
> ##	Step 2: Run proTRAC program	##
> ##########################################
> if(isTRUE(picall)) {
+ 	f_res <- run_proTRAC(fq, ref_gen, num_clusters, wd, results_dir, gid, verbose)
+ } else if(fa != "FALSE") {
+ 	spl <- strsplit(as.character(fa), "/")
+         f_res <- paste(results_dir, spl[[1]][length(spl[[1]])], sep="")	
+ 	system(paste("cp", fa, f_res, sep=" "))
+ 
+ 	f_res <- resuffix(f_res, ".bed")
+ 
+ 	fst <- read.fasta(as.character(fa), as.string=TRUE, forceDNAtolower=FALSE)
+ 	num_clusters <- length(fst)
+ 	
+ 	temp <- strsplit(as.character(attr(fst, "name")), ":", fixed=TRUE)   ###FIXXX: stop with error if not found
+ 	one<-NULL; temp2<-NULL;
+ 	for(ii in 1:length(temp)) { one <- append(one, as.character(temp[[ii]][1])); temp2 <- append(temp2, as.character(temp[[ii]][2])) }
+ 
+ 	temp <- strsplit(temp2, "..", fixed=TRUE)
+ 	two<-NULL; three<-NULL;
+ 	for(ii in 1:length(temp)) { two <- append(two, as.character(temp[[ii]][1])); three <- append(three, as.character(temp[[ii]][2])) }
+ 	pi_loci <- data.frame(one, two, three)
+ 
+ 	write.table(pi_loci, f_res, quote=FALSE, col.names=FALSE, row.names=FALSE, sep="\t")
+ } else {
+ 	spl <- strsplit(bed,"/")
+ 	f_res <- paste(results_dir, spl[[1]][length(spl[[1]])], sep="")
+ 	file.copy(bed, f_res)
+ }
Error in run_proTRAC(fq, ref_gen, num_clusters, wd, results_dir, gid,  : 
  unused argument (verbose)
Execution halted

**Comment by pschreiner** [comment]
I have had a few issues reported due to the version of proTRAC that was being used.  This software was built for use with proTRAC_2.1, but there have been several updates to that tool.  An easy workaround is to run proTRAC using the version that you have, and then run piClusterBusteR with the proTRAC piRNA cluster calls (using the "-bed" option).
